"use client";

import { Bell, Calendar, CircleAlert, Inbox, MessageCircle, Phone, PhoneMissed, UserPlus, ArrowRight } from "lucide-react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import styles from "./notifications-panel.module.css";

type Notification = { id: string; kind: string; title: string; body: string | null; deal_id: string | null; contact_id: string | null; created_at: string; read_at: string | null };
const PAGE_SIZE = 20;
const icons = { incoming_call: Phone, new_lead: Inbox, new_message: MessageCircle, task_overdue: CircleAlert, postponed_due: Calendar, phone_missed: PhoneMissed, deal_stage_changed: ArrowRight, deal_assigned: UserPlus } as const;
const formatTime = (value: string) => new Intl.DateTimeFormat("ru-RU", { hour: "2-digit", minute: "2-digit" }).format(new Date(value));
const dayName = (value: string) => { const date = new Date(value); const today = new Date(); const yesterday = new Date(); yesterday.setDate(today.getDate() - 1); if (date.toDateString() === today.toDateString()) return "Сегодня"; if (date.toDateString() === yesterday.toDateString()) return "Вчера"; return new Intl.DateTimeFormat("ru-RU", { day: "numeric", month: "long" }).format(date); };

export function NotificationsPanel({ role }: { role: string }) {
  const [open, setOpen] = useState(false); const [filter, setFilter] = useState<"all" | "unread">("all"); const [items, setItems] = useState<Notification[]>([]); const [unread, setUnread] = useState(0); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null); const [hasMore, setHasMore] = useState(true); const rootRef = useRef<HTMLDivElement>(null); const supabase = useMemo(() => createClient(), []); const pathname = usePathname();
  const load = useCallback(async (reset = false) => { setLoading(true); setError(null); const from = reset ? 0 : items.length; let query = supabase.from("notifications").select("id,kind,title,body,deal_id,contact_id,created_at,read_at", { count: "exact" }).order("created_at", { ascending: false }).range(from, from + PAGE_SIZE - 1); if (filter === "unread") query = query.is("read_at", null); const result = await query; const unreadResult = await supabase.from("notifications").select("id", { count: "exact", head: true }).is("read_at", null); if (result.error || unreadResult.error) setError("Не удалось загрузить уведомления"); else { const next = (result.data ?? []) as Notification[]; setItems(reset ? next : [...items, ...next]); setHasMore(next.length === PAGE_SIZE); setUnread(unreadResult.count ?? 0); } setLoading(false); }, [filter, items, supabase]);
  useEffect(() => {
    if (!open) return;
    const timer = window.setTimeout(() => void load(true), 0);
    return () => window.clearTimeout(timer);
  }, [open, filter]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => { const handler = (event: MouseEvent) => { if (open && rootRef.current && !rootRef.current.contains(event.target as Node)) setOpen(false); }; const escape = (event: KeyboardEvent) => { if (event.key === "Escape") setOpen(false); }; document.addEventListener("mousedown", handler); document.addEventListener("keydown", escape); return () => { document.removeEventListener("mousedown", handler); document.removeEventListener("keydown", escape); }; }, [open]);
  if (role === "builder") return null;
  const markRead = async (id: string) => { await supabase.from("notifications").update({ read_at: new Date().toISOString() }).eq("id", id); setItems((current) => current.map((item) => item.id === id ? { ...item, read_at: new Date().toISOString() } : item)); setUnread((current) => Math.max(0, current - 1)); };
  const markAll = async () => { await supabase.from("notifications").update({ read_at: new Date().toISOString() }).is("read_at", null); setItems((current) => current.map((item) => ({ ...item, read_at: item.read_at ?? new Date().toISOString() }))); setUnread(0); };
  const grouped = items.reduce<Record<string, Notification[]>>((groups, item) => { const key = dayName(item.created_at); (groups[key] ??= []).push(item); return groups; }, {});
  return <div className={styles.root} ref={rootRef}><button className={styles.bell} aria-label={`Уведомления${unread ? `, ${unread} непрочитанных` : ""}`} aria-expanded={open} onClick={() => setOpen((value) => !value)}><Bell size={17} />{unread > 0 && <span className={styles.count}>{unread > 99 ? "99+" : unread}</span>}</button>{open && <section className={styles.panel} aria-label="Уведомления"><div className={styles.header}><h2>Уведомления</h2><button className={styles.quiet} disabled={!unread} onClick={() => void markAll()}>Прочитать все</button></div><div className={styles.tabs}><button className={`${styles.tab} ${filter === "all" ? styles.tabActive : ""}`} onClick={() => setFilter("all")}>Все</button><button className={`${styles.tab} ${filter === "unread" ? styles.tabActive : ""}`} onClick={() => setFilter("unread")}>Непрочитанные{unread ? ` ${unread}` : ""}</button></div><div className={styles.body}>{loading && !items.length ? <div className={styles.status}>Загрузка…</div> : error ? <div className={`${styles.status} ${styles.error}`}>{error}</div> : !items.length ? <div className={styles.status}>{filter === "unread" ? "Нет непрочитанных уведомлений" : "Уведомлений пока нет"}</div> : Object.entries(grouped).map(([day, dayItems]) => <div key={day}><div className={styles.groupTitle}>{day}</div>{dayItems.map((item) => { const Icon = icons[item.kind as keyof typeof icons] ?? Bell; const target = item.deal_id ? `/deals/${item.deal_id}` : item.contact_id ? `/contacts/${item.contact_id}` : pathname; return <Link href={target} key={item.id} className={`${styles.row} ${!item.read_at ? styles.unread : ""}`} onClick={() => { if (!item.read_at) void markRead(item.id); setOpen(false); }}><span className={styles.icon}><Icon size={15} /></span><span className={styles.copy}><span className={styles.title}>{item.title}</span><span className={styles.bodyText}>{item.body ?? ""}</span></span><time className={styles.time} dateTime={item.created_at}>{formatTime(item.created_at)}</time><span className={styles.dot} aria-hidden="true" style={{ opacity: item.read_at ? 0 : 1 }} /></Link>; })}</div>)}</div>{hasMore && !error && <div className={styles.footer}><button className={styles.quiet} disabled={loading} onClick={() => void load()}>{loading ? "Загрузка…" : "Показать ещё"}</button></div>}</section>}</div>;
}
