// Контекст транскрибации звонков IsraGrup: keyword biasing для MAI-Transcribe-2.
// Источник фраз: research/isragrup-transcription-context.md, блок phrase list.
// Только имена и термины (бренд, проекты, основатели, география, адрес,
// ориентиры, термины недвижимости); цен и сроков сдачи здесь нет.

export const ISRAGRUP_TRANSCRIPTION_PHRASES = [
  "IsraGrup",
  "ISRAGRUP",
  "SRL IsraGrup",
  "Select New Town",
  "Next New Town",
  "New Town",
  "Casa Verde",
  "Style House",
  "Hi-Tech Poiana Domnească",
  "Tudor Spînachi",
  "Ion Spînachi",
  "Chișinău",
  "Кишинёв",
  "Durlești",
  "Дурлешты",
  "Дурлешт",
  "Cartușa",
  "Картуша",
  "str. Cartușa 95/5",
  "Hyperion",
  "Orizont",
  "Rehau",
  "REHAU",
  "керамоблок",
  "керамо-блоки",
  "cărămidă roșie",
  "vată minerală",
  "variantă albă",
  "белый вариант",
  "planimetrii",
  "планировки",
  "parcare subterană",
  "подземная парковка",
  "curte închisă",
  "закрытый двор",
  "debara",
  "кладовые",
  "prima rată",
  "первый взнос",
  "avans",
  "achitare în rate",
  "рассрочка",
  "credit ipotecar",
  "ипотека",
  "procură generală",
  "доверенность",
  "WhatsApp",
  "Viber",
] as const;

export type IsragrupTranscriptionPhrase =
  (typeof ISRAGRUP_TRANSCRIPTION_PHRASES)[number];
