import { Check, CheckCircle2, Circle, List, Plus, Search, SlidersHorizontal, Tag } from "lucide-react";
import { getCurrentProfile } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";

type TaskRow = { id: string; deal_id: string | null; contact_id: string | null; assignee_id: string | null; type_id: string | null; title: string | null; due_at: string; done_at: string | null; result_text?: string | null };
type ViewTask = TaskRow & { typeName: string; contactName: string; stageName: string; assigneeName: string; dueLabel: string; overdueLabel?: string };
const typeFallback: Record<string, string> = { call: "Звонок", meeting: "Встреча", presentation: "Презентация", message: "Написать в мессенджер", documents: "Документы" };
const formatter = new Intl.DateTimeFormat("ru-RU", { timeZone: "Europe/Chisinau", day: "numeric", month: "short" });
const timeFormatter = new Intl.DateTimeFormat("ru-RU", { timeZone: "Europe/Chisinau", hour: "2-digit", minute: "2-digit" });
const localDate = (value: Date) => new Intl.DateTimeFormat("en-CA", { timeZone: "Europe/Chisinau", year: "numeric", month: "2-digit", day: "2-digit" }).format(value);
const addDays = (value: string, days: number) => { const date = new Date(`${value}T12:00:00Z`); date.setUTCDate(date.getUTCDate() + days); return date.toISOString().slice(0, 10); };
const initials = (name: string) => name.split(/\s+/).filter(Boolean).slice(0, 2).map((part) => part[0]).join("").toUpperCase() || "—";

export default async function TasksPage() {
  const profile = await getCurrentProfile(); if (!profile) return null;
  const supabase = await createClient();
  const result = await supabase.from("tasks").select("id, deal_id, contact_id, assignee_id, type_id, title, due_at, done_at, result_text", { count: "exact" }).eq("assignee_id", profile.id).order("due_at").order("id").range(0, 99);
  if (result.error) throw new Error(`Задачи: ${result.error.message}`);
  const rows = (result.data ?? []) as TaskRow[];
  const ids = <T extends string>(values: (T | null | undefined)[]) => [...new Set(values.filter((value): value is T => Boolean(value)))];
  const [types, contacts, deals, people] = await Promise.all([
    supabase.from("task_types").select("id, name, code").in("id", ids(rows.map((row) => row.type_id))),
    supabase.from("contacts").select("id, full_name").in("id", ids(rows.map((row) => row.contact_id))),
    supabase.from("deals").select("id, stage_id").in("id", ids(rows.map((row) => row.deal_id))),
    supabase.from("profiles").select("id, full_name").in("id", ids(rows.map((row) => row.assignee_id))),
  ]);
  const stages = await supabase.from("stages").select("id, name").in("id", ids((deals.data ?? []).map((deal) => deal.stage_id)));
  const typeMap = new Map((types.data ?? []).map((item) => [item.id, item])); const contactMap = new Map((contacts.data ?? []).map((item) => [item.id, item.full_name])); const dealMap = new Map((deals.data ?? []).map((item) => [item.id, item.stage_id])); const stageMap = new Map((stages.data ?? []).map((item) => [item.id, item.name])); const peopleMap = new Map((people.data ?? []).map((item) => [item.id, item.full_name]));
  const today = localDate(new Date()); const tomorrow = addDays(today, 1); const weekday = new Date(`${today}T12:00:00Z`).getUTCDay(); const weekEnd = addDays(today, weekday === 0 ? 0 : 7 - weekday);
  const viewTasks: ViewTask[] = rows.map((row) => { const type = typeMap.get(row.type_id ?? ""); const dueDate = localDate(new Date(row.due_at)); const delta = Math.round((Date.parse(`${today}T12:00:00Z`) - Date.parse(`${dueDate}T12:00:00Z`)) / 86400000); return { ...row, typeName: type?.name ?? typeFallback[type?.code ?? ""] ?? "Задача", contactName: contactMap.get(row.contact_id ?? "") ?? "Контакт не указан", stageName: stageMap.get(dealMap.get(row.deal_id ?? "") ?? "") ?? "Без этапа", assigneeName: peopleMap.get(row.assignee_id ?? "") ?? profile.full_name, dueLabel: dueDate === today || dueDate === tomorrow ? timeFormatter.format(new Date(row.due_at)) : formatter.format(new Date(row.due_at)), overdueLabel: delta > 0 ? `просрочено ${delta} дн` : undefined }; });
  const groups = [{ key: "overdue", label: "Просрочено", tone: "danger", tasks: viewTasks.filter((task) => !task.done_at && localDate(new Date(task.due_at)) < today) }, { key: "today", label: "Сегодня", tasks: viewTasks.filter((task) => localDate(new Date(task.due_at)) === today) }, { key: "tomorrow", label: "Завтра", tasks: viewTasks.filter((task) => localDate(new Date(task.due_at)) === tomorrow) }, { key: "week", label: "На этой неделе", tasks: viewTasks.filter((task) => { const date = localDate(new Date(task.due_at)); return date > tomorrow && date <= weekEnd; }) }, { key: "later", label: "Позже", tasks: viewTasks.filter((task) => localDate(new Date(task.due_at)) > weekEnd) }].filter((group) => group.tasks.length);
  const count = (key: string) => groups.find((group) => group.key === key)?.tasks.length ?? 0;
  return <div className="tasks-page"><header className="tasks-header"><h1>Задачи</h1><span className="header-spacer" /><span className="tasks-total">{result.count ?? rows.length}</span></header><div className="tasks-toolbar"><div className="view-switch"><span className="view-switch-active"><List size={14} />Список</span><span><Tag size={14} />Календарь</span></div><span className="header-spacer" /><span className="task-icon-button" aria-label="Поиск"><Search size={15} /></span><span className="task-primary-button is-deferred" title="Создание задач появится позже"><Plus size={15} />Задача</span></div><div className="tasks-filterbar"><span className="filter-control"><SlidersHorizontal size={14} />Сортировка</span><span className="filter-control">Фильтр</span><span className="filter-chip">Ответственный: {profile.full_name}</span><span className="header-spacer" /><span className="task-counter danger"><i />Просрочено {count("overdue")}</span><span className="task-counter blue"><i />Сегодня {count("today")}</span><span className="task-counter"><i />Завтра {count("tomorrow")}</span></div><main className="task-list">{groups.map((group) => <section className="task-group" key={group.key}><div className={`task-group-header ${group.tone === "danger" ? "is-danger" : ""}`}><span>{group.label}</span><b>{group.tasks.length}</b></div>{group.tasks.map((task) => <div className={`task-row ${task.done_at ? "is-done" : ""}`} key={task.id}><span className={`task-check ${task.done_at ? "is-complete" : ""}`}>{task.done_at ? <Check size={11} /> : <Circle size={15} />}</span><span className="task-type" title={task.typeName}>{task.typeName.slice(0, 1)}</span><span className="task-main"><strong>{task.title?.trim() || `${task.typeName} — без названия`}</strong><span><a href={task.contactName === "Контакт не указан" ? undefined : "/contacts"}>{task.contactName}</a><em>·</em>{task.stageName}</span></span><span className={`task-due ${task.overdueLabel ? "is-overdue" : ""}`}>{task.overdueLabel ?? task.dueLabel}</span><span className="task-avatar" title={task.assigneeName}>{initials(task.assigneeName)}</span></div>)}{group.tasks.filter((task) => task.done_at && task.result_text?.trim()).map((task) => <div className="task-result" key={`${task.id}-result`}><CheckCircle2 size={14} />{task.result_text}</div>)}</section>)}{!groups.length && <div className="tasks-empty">Задач пока нет</div>}</main></div>;
}
